return {
-- Table: {1}
{
   {2},
   ["profile"]={3},
   ["config"]={4},
   ["debug"]={5},
   ["RotationDrop"]=1,
   ["toggleBar"]={6},
   ["toggles"]={7},
},
-- Table: {2}
{
   ["Wise TargetDrop"]=1,
   ["Multi-DoT LimitCheck"]=false,
   ["Auto ShapeshiftsCheck"]=true,
   ["Brutal Slash TargetsCheck"]=false,
   ["Enemies EngineSection"]=true,
   ["Primal Wrath UsageDrop"]=1,
   ["Revive - TargetCheck"]=false,
   ["Enrages HandlerCheck"]=false,
   ["Cooldown ModeDrop"]=3,
   ["Target Validation DebugCheck"]=true,
   ["OpenerCheck"]=true,
   ["Pot/StonedCheck"]=true,
   ["currentPage"]=7,
   ["Auto-Sell/RepairCheck"]=true,
   ["Skull FirstCheck"]=true,
   ["Augment RuneCheck"]=true,
   ["Pause ModeDrop"]=2,
   ["Snipe Tiger's FuryDrop"]=1,
   ["Primal Wrath UsageCheck"]=false,
   ["Fall TimerCheck"]=false,
   ["TrinketsCheck"]=false,
   ["DefensiveSection"]=true,
   ["Rotation ModeCheck"]=true,
   ["Rotation ModeDrop"]=4,
   ["Dispel Only WhitelistCheck"]=false,
   ["Bot Update RateCheck"]=false,
   ["Tiger's FuryCheck"]=true,
   ["SwiftmendStatus"]=55,
   ["WildgrowthStatus"]=45,
   ["Break Crowd ControlCheck"]=false,
   ["Purge Only WhitelistCheck"]=false,
   ["Display FailcastsCheck"]=false,
   ["Brutal Slash in OpenerDrop"]=1,
   ["RenewalCheck"]=true,
   ["Auto HealDrop"]=1,
   ["Overlay MessagesCheck"]=true,
   ["Pause IntervalStatus"]=0.25,
   ["TrinketsDrop"]=1,
   ["WildgrowthCheck"]=true,
   ["MaimCheck"]=true,
   ["InterruptsSection"]=true,
   ["SwiftmendCheck"]=true,
   ["APL ModeCheck"]=false,
   ["Cast DebugCheck"]=false,
   ["Accept QueuesCheck"]=true,
   ["Interrupt AtStatus"]=0,
   ["Load Prior Saved SettingsCheck"]=false,
   ["RegrowthStatus"]=80,
   ["Mute QueueCheck"]=false,
   ["Reset Saved ProfilesCheck"]=false,
   ["Target Dynamic TargetCheck"]=false,
   ["Ferocious Bite ExecuteCheck"]=false,
   ["Load Prior Saved SettingsDrop"]=1,
   ["Survival InstinctsStatus"]=40,
   ["Pause ModeCheck"]=true,
   ["Multi-DoT LimitStatus"]=8,
   ["Remove Corruption - TargetDrop"]=3,
   ["Heirloom NeckStatus"]=60,
   ["Pause IntervalCheck"]=false,
   ["Enhanced Time to DieCheck"]=true,
   ["Remove CorruptionCheck"]=true,
   ["Heirloom NeckCheck"]=true,
   ["RenewalStatus"]=35,
   ["Use EssenceCheck"]=true,
   ["Rebirth - TargetCheck"]=false,
   ["Toggle KeysSection"]=true,
   ["Talent AnywhereCheck"]=false,
   ["Interrupt AtCheck"]=false,
   ["RegrowthCheck"]=true,
   ["RacialCheck"]=true,
   ["Auto DelayCheck"]=false,
   ["Death Cat ModeCheck"]=false,
   ["Interrupt MarkCheck"]=false,
   ["Prioritize TotemsCheck"]=true,
   ["APL ModeDrop"]=1,
   ["Save/Load SettingsSection"]=true,
   ["Defensive ModeCheck"]=false,
   ["Berserk/IncarnationCheck"]=true,
   ["Displacer Beast / Wild ChargeCheck"]=false,
   ["Auto HealCheck"]=false,
   ["Tank ThreatCheck"]=false,
   ["Regrowth - OoCDrop"]=1,
   ["Don't break CCsCheck"]=true,
   ["Forced BurnCheck"]=true,
   ["Interrupt TargetCheck"]=false,
   ["Reset OptionsCheck"]=false,
   ["Avoid ShieldsCheck"]=true,
   ["CooldownsSection"]=true,
   ["PotionCheck"]=true,
   ["Dynamic TargettingDrop"]=2,
   ["ElixirDrop"]=2,
   ["Revive - TargetDrop"]=2,
   ["Regrowth - InCDrop"]=2,
   ["GeneralSection"]=true,
   ["DPS TestingCheck"]=true,
   ["Wise TargetCheck"]=false,
   ["Only Known UnitsCheck"]=false,
   ["Skull BashCheck"]=true,
   ["Queue CastingCheck"]=false,
   ["Brutal Slash TargetsStatus"]=3,
   ["Snipe Tiger's FuryCheck"]=false,
   ["Auto LootStatus"]=0.5,
   ["Notify Not UnlockedCheck"]=false,
   ["Prowl ModeCheck"]=false,
   ["Crowd ControlCheck"]=false,
   ["Attack MC TargetsCheck"]=true,
   ["RejuvenationStatus"]=75,
   ["Base OptionsSection"]=true,
   ["Bot Update RateStatus"]=0.1,
   ["Ferocious Bite ExecuteDrop"]=2,
   ["Remove Corruption - TargetCheck"]=false,
   ["Safe Damage CheckCheck"]=true,
   ["Pre-Pull TimerCheck"]=false,
   ["Defensive ModeDrop"]=6,
   ["RejuvenationCheck"]=true,
   ["Prowl ModeDrop"]=6,
   ["Rebirth - TargetDrop"]=2,
   ["Hostiles OnlyCheck"]=true,
   ["Notify Not UnlockedStatus"]=10,
   ["Brutal Slash in OpenerCheck"]=false,
   ["DPS TestingStatus"]=5,
   ["Addon Debug MessagesCheck"]=false,
   ["Pot/StonedStatus"]=60,
   ["SootheCheck"]=true,
   ["Rotation LogCheck"]=false,
   ["Interrupt Only WhitelistCheck"]=false,
   ["Interrupt TargetDrop"]=1,
   ["Interrupt ModeCheck"]=false,
   ["Auto LootCheck"]=true,
   ["ElixirCheck"]=false,
   ["Interrupt ModeDrop"]=6,
   ["Cleave ModeCheck"]=false,
   ["Pre-Pull TimerStatus"]=5,
   ["Cooldown ModeCheck"]=true,
   ["Cleave ModeDrop"]=6,
   ["RebirthCheck"]=true,
   ["Interrupt MarkDrop"]=8,
   ["Regrowth - InCCheck"]=false,
   ["Fall TimerStatus"]=2,
   ["Perma Fire CatCheck"]=false,
   ["Mighty BashCheck"]=true,
   ["Survival InstinctsCheck"]=true,
   ["Ignore CombatCheck"]=false,
   ["Regrowth - OoCCheck"]=false,
   ["ReviveCheck"]=true,
   ["Dynamic TargettingCheck"]=true,
},
-- Table: {3}
{
   ["relativeTo"]="UIParent",
   ["point"]="TOP",
   ["active"]=false,
   ["yOfs"]=816.00006103516,
   ["xOfs"]=0,
   ["xOfs2"]=1279,
   ["width"]=275.00003051758,
   ["relativeTo2"]="UIParent",
   ["relativePoint"]="BOTTOM",
   ["height"]=400,
   ["relativePoint2"]="LEFT",
   ["point2"]="LEFT",
   ["yOfs2"]=0,
},
-- Table: {4}
{
   ["relativeTo"]="UIParent",
   ["point"]="TOP",
   ["active"]=true,
   ["yOfs"]=889.00018310547,
   ["xOfs"]=0,
   ["xOfs2"]=419,
   ["width"]=275.00003051758,
   ["relativeTo2"]="UIParent",
   ["relativePoint"]="BOTTOM",
   ["height"]=400,
   ["relativePoint2"]="LEFT",
   ["point2"]="LEFT",
   ["yOfs2"]=0,
},
-- Table: {5}
{
   ["yOfs"]=0,
   ["relativeTo"]="UIParent",
   ["point"]="CENTER",
   ["active"]=false,
   ["height"]=249.99996948242,
   ["xOfs"]=0,
   ["relativePoint"]="CENTER",
   ["width"]=299.99993896484,
},
-- Table: {6}
{
   ["size"]=36,
   ["pos"]={8},
},
-- Table: {7}
{
   ["Rotation"]=1,
   ["Prowl"]=1,
   ["Main"]=1,
   ["Power"]=1,
   ["Interrupt"]=1,
   ["Cooldown"]=1,
   ["Defensive"]=1,
   ["Cleave"]=1,
},
-- Table: {8}
{
   ["anchor"]="RIGHT",
   ["x"]=-281.44528198242,
   ["y"]=-165.55563354492,
},
}